- name: provider templates
  template:
    src: "{{item}}-provider.j2"
    dest: "{{workdir}}00-provider-{{item}}.tf"
  with_items: "{{terraform_providers|default(['aws'])}}"

- name: remote states
  template:
    src: "remotestate.j2"
    dest: "{{workdir}}01-remotestate.tf"

- name: import state from other terraform projects
  template:
    src: "importstate.j2"
    dest: "{{workdir}}02-importstate.tf"

- name: local variables
  template:
    src: "locals.j2"
    dest: "{{workdir}}03-locals.tf"

- name: define security groups
  template:
    src: aws_security_groups.j2
    dest: "{{workdir}}10-security_groups.tf"
  when:
    security_groups is defined
